app/controllers/user_controller.py
from flask import Blueprint, render_template

login_route = Blueprint('login_route', __name__)
register_route = Blueprint('register_route', __name__)

@login_route.route('/login', methods=['GET', 'POST'])
def login():
    # if request.method == 'POST':
    #     email = request.form['email']
    #     password = request.form['password']

    #     user = User.query.filter_by(email=email).first()
    #     if user and check_password_hash(user.password, password):
    #         login_user(user)
    #         flash('Login successful!', 'success')
    #         return redirect(url_for('dashboard'))  # Rediriger vers le tableau de bord après la connexion
    #     else:
    #         flash('Login failed. Check your email and/or password', 'danger')
    #         return redirect(url_for('login'))

    return render_template('login.html')

@register_route.route('/register', methods=['GET', 'POST'])
def register():
    # if request.method == 'POST':
    #     username = request.form['username']
    #     email = request.form['email']
    #     password = request.form['password']

    #     # Vérifier si l'utilisateur existe déjà
    #     user_exists = User.query.filter_by(email=email).first()
    #     if user_exists:
    #         flash('Email already registered', 'danger')
    #         return redirect(url_for('register'))
        
    #     # Créer un nouvel utilisateur
    #     hashed_password = generate_password_hash(password, method='sha256')
    #     new_user = User(username=username, email=email, password=hashed_password)
    #     db.session.add(new_user)
    #     db.session.commit()

    #     flash('Your account has been created!', 'success')
    #     return redirect(url_for('home'))
    return render_template('register.html')

app/routes/register_routes.py
from flask import Blueprint, render_template

register_route = Blueprint('register_route', __name__)

@register_route.route('/register', methods=['GET', 'POST'])
def register():
    # if request.method == 'POST':
    #     username = request.form['username']
    #     email = request.form['email']
    #     password = request.form['password']

    #     # Vérifier si l'utilisateur existe déjà
    #     user_exists = User.query.filter_by(email=email).first()
    #     if user_exists:
    #         flash('Email already registered', 'danger')
    #         return redirect(url_for('register'))
        
    #     # Créer un nouvel utilisateur
    #     hashed_password = generate_password_hash(password, method='sha256')
    #     new_user = User(username=username, email=email, password=hashed_password)
    #     db.session.add(new_user)
    #     db.session.commit()

    #     flash('Your account has been created!', 'success')
    #     return redirect(url_for('home'))
    return render_template('register.html')

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Traduction de Texte</title>
    <link rel="stylesheet" href="">
</head>
<body>
    <a href="{{ url_for('login_route.login') }}">Connexion</a>
    <a href="{{ url_for('register_route.register') }}">Register</a>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <h1>Login</h1>
  <form method="POST" action="{{ url_for('login_route.login')}}">
    <label for="email">Email:</label>
    <input type="email" id="email" name="email" required>
    <br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password" required>
    <br>
    <input type="submit" value="Login">
  </form>
</body>
</html>

app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Register</h1>
    <form method="POST" action="{{ url_for('register_route.register') }}">
      <label for="username">Username:</label>
      <input type="text" id="username" name="username" required>
      <br>
      <label for="email">Email:</label>
      <input type="email" id="email" name="email" required>
      <br>
      <label for="password">Password:</label>
      <input type="password" id="password" name="password" required>
      <br>
      <input type="submit" value="Register">
    </form>
</body>
</html>